# Generated by Django 3.2.9 on 2021-11-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_landmark_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
