# Generated by Django 3.2.9 on 2021-12-16 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_landmark_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='auth.user'),
            preserve_default=False,
        ),
    ]
