# Generated by Django 3.2.9 on 2021-12-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_landmark_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
